
import costanza.Job;
import costanza.Options;

public class AlgorithmPanel extends java.awt.Panel {

	MainPanel mainPanel;
	
	AlgorithmPanel(MainPanel mainPanel) {
		initComponents();
		this.mainPanel = mainPanel;
	}

	Job getInvertJob() {
		String processorId;
		if (invertCheckbox.getState() == true) {
			processorId = "invert";
		} else {
			processorId = "null";
		}
		return new Job(processorId, null);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invertCheckbox = new java.awt.Checkbox();
        panel1 = new java.awt.Panel();
        cancelButton = new java.awt.Button();
        startButton = new java.awt.Button();

        setLayout(new java.awt.BorderLayout());

        invertCheckbox.setLabel("Invert image(s) before processing.");
        add(invertCheckbox, java.awt.BorderLayout.CENTER);

        cancelButton.setLabel("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        panel1.add(cancelButton);

        startButton.setLabel("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        panel1.add(startButton);

        add(panel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
		mainPanel.startButtonPressed();
	}//GEN-LAST:event_startButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		mainPanel.cancelButtonPressed();
	}//GEN-LAST:event_cancelButtonActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cancelButton;
    private java.awt.Checkbox invertCheckbox;
    private java.awt.Panel panel1;
    private java.awt.Button startButton;
    // End of variables declaration//GEN-END:variables
	
}
