
import costanza.Job;
import costanza.Options;
import costanza.Queue;

public class BackGroundFinderIntensityOption extends java.awt.Panel implements ProcessorOption {
	public BackGroundFinderIntensityOption() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        intensityThresholdLabel = new java.awt.Label();
        intensityThresholdTextField = new java.awt.TextField();

        setLayout(new java.awt.GridBagLayout());

        intensityThresholdLabel.setText("Intensity threshold:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(intensityThresholdLabel, gridBagConstraints);

        intensityThresholdTextField.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(intensityThresholdTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

	public java.awt.Panel getPanel() {
		return this;
	}

	public String getProcessorName() {
		return "Background extraction";
	}

	public void addJobs(Queue jobs) throws Exception {
		Options options = new Options();
		options.addOption("threshold", new Float(intensityThresholdTextField.getText()));
		jobs.addJob(new Job("backgroundextractor", options));
	}
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label intensityThresholdLabel;
    private java.awt.TextField intensityThresholdTextField;
    // End of variables declaration//GEN-END:variables
	
}
