public class MainPanel extends java.awt.Panel {

    MainPanel(Costanza_Plugin plugin) {
	initComponents();
    }

    boolean getInvertCheckboxState() {
	throw new UnsupportedOperationException("Not yet implemented");
    }

    float getMeanFieldRadiusValue() {
	throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
