
public class OptionPanel extends java.awt.Panel {

	ProcessorMenuPanel parentPanel;
	ProcessorOption processorOption;
	
	public OptionPanel(ProcessorMenuPanel parentPanel, ProcessorOption processorOption) {
		this.parentPanel = parentPanel;
		this.processorOption = processorOption;
		initComponents();
		optionPanel.add(processorOption.getPanel());
		processorNameLabel.setText(processorOption.getProcessorName());
	}
	
	public ProcessorOption getProcessorOption() {
		return processorOption;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        removeButton = new java.awt.Button();
        processorNameLabel = new java.awt.Label();
        optionPanel = new java.awt.Panel();

        setLayout(new java.awt.GridBagLayout());

        removeButton.setLabel("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        add(removeButton, new java.awt.GridBagConstraints());

        processorNameLabel.setText("processorName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(processorNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(optionPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
	private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
		parentPanel.removeOption(this);
	}//GEN-LAST:event_removeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel optionPanel;
    private java.awt.Label processorNameLabel;
    private java.awt.Button removeButton;
    // End of variables declaration//GEN-END:variables
}
