
import costanza.Job;
import costanza.Options;
import costanza.Queue;

public class PeakRemoverOption extends java.awt.Panel implements ProcessorOption {

    public PeakRemoverOption() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sizeThresholdLabel = new java.awt.Label();
        sizeThresholdTextField = new java.awt.TextField();
        intensityThresholdLabel = new java.awt.Label();
        intensityThresholdTextField = new java.awt.TextField();

        setLayout(new java.awt.GridBagLayout());

        sizeThresholdLabel.setText("Size threshold:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(sizeThresholdLabel, gridBagConstraints);

        sizeThresholdTextField.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(sizeThresholdTextField, gridBagConstraints);

        intensityThresholdLabel.setText("Intensity threshold:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(intensityThresholdLabel, gridBagConstraints);

        intensityThresholdTextField.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(intensityThresholdTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    public java.awt.Panel getPanel() {
        return this;
    }

    public String getProcessorName() {
        return "Peak remover";
    }

    public void addJobs(Queue jobs) throws Exception {
        jobs.addJob(new Job("peakremover", getOptions()));
    }

    public Options getOptions() throws Exception {
        Options options = new Options();
        options.addOption("sizeThreshold", new Float(sizeThresholdTextField.getText()));
        float threshold = new Float(intensityThresholdTextField.getText()).floatValue();
        options.addOption("intensityLevelsNumber", ((OptionPanel)getParent().getParent()).getParentPanel().getFrame().getIntensityLevelsNumber());
        options.addOption("intensityThreshold", new Float(threshold));
        return options;
    }
    
    public void setFromOptions(Options o) throws Exception {
//        System.out.println(getProcessorName());
//        System.out.println(o.toString());
        Float size = (Float)o.getOptionValue("sizeThreshold");
        if(o.hasOption("intensityLevelsNumber")){
            Integer nIntLev = (Integer)o.getOptionValue("intensityLevelsNumber");
            ((OptionPanel)getParent().getParent()).getParentPanel().getFrame().setIntensityLevelsNumber(nIntLev);
        }
        Float threshold = (Float)o.getOptionValue("intensityThreshold");
        sizeThresholdTextField.setText(size.toString());
        intensityThresholdTextField.setText(threshold.toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label intensityThresholdLabel;
    private java.awt.TextField intensityThresholdTextField;
    private java.awt.Label sizeThresholdLabel;
    private java.awt.TextField sizeThresholdTextField;
    // End of variables declaration//GEN-END:variables
}
