
import costanza.Factory;
import costanza.Queue;
import java.util.logging.Level;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ProcessorMenuPanel extends java.awt.Panel {

	private java.util.LinkedList<OptionPanel> optionPanelList;
	private MainFrame frame;
	private Factory<ProcessorOption> factory;

	public ProcessorMenuPanel(MainFrame frame) {
		this.frame = frame;
		factory = new Factory<ProcessorOption>();
		optionPanelList = new java.util.LinkedList<OptionPanel>();
		initComponents();
	}

	public void addProcessorOptionToMenu(String name, Class<? extends ProcessorOption> processorOptionClass) {
		processorOptionChoice.add(name);
		factory.register(name, processorOptionClass);
	}

	public void addJobs(Queue jobs) throws Exception {
		java.util.Iterator<OptionPanel> iterator = optionPanelList.iterator();

		while (iterator.hasNext()) {
			OptionPanel optionPanel = iterator.next();
			ProcessorOption processorOption = optionPanel.getProcessorOption();
			processorOption.addJobs(jobs);
		}
	}

	public void removeOption(OptionPanel optionPanel) {
		displayPanel.remove(optionPanel);
		optionPanelList.remove(optionPanel);
		frame.update();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new java.awt.Panel();
        addButton = new java.awt.Button();
        processorOptionChoice = new java.awt.Choice();
        displayPanel = new java.awt.Panel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        northPanel.setLayout(new java.awt.GridBagLayout());

        addButton.setLabel("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        northPanel.add(addButton, new java.awt.GridBagConstraints());
        northPanel.add(processorOptionChoice, new java.awt.GridBagConstraints());

        add(northPanel);

        displayPanel.setLayout(new javax.swing.BoxLayout(displayPanel, javax.swing.BoxLayout.Y_AXIS));
        add(displayPanel);
    }// </editor-fold>//GEN-END:initComponents
	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
		try {
			String name = processorOptionChoice.getSelectedItem();
			addOptionPanel(name);
		} catch (Exception ex) {
			Logger.getLogger(ProcessorMenuPanel.class.getName()).log(Level.SEVERE, null, ex);
		}
	}//GEN-LAST:event_addButtonActionPerformed

	public void addOptionPanel(String name) throws Exception {
		OptionPanel optionPanel = new OptionPanel(this, factory.create(name));
		displayPanel.add(optionPanel);
		optionPanelList.add(optionPanel);
		frame.update();
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addButton;
    private java.awt.Panel displayPanel;
    private java.awt.Panel northPanel;
    private java.awt.Choice processorOptionChoice;
    // End of variables declaration//GEN-END:variables
}
