
public class ScaleOptionPanel extends java.awt.Panel {

	private MainFrame frame;
	private ij.measure.Calibration calibration;

	public ScaleOptionPanel(MainFrame frame) {
		initComponents();
		this.frame = frame;
	}

	void setCalibration(ij.measure.Calibration calibration) {
		this.calibration = calibration;
		xScaleTextField.setText(Double.toString(calibration.pixelWidth));
		yScaleTextField.setText(Double.toString(calibration.pixelHeight));
		zScaleTextField.setText(Double.toString(calibration.pixelDepth));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scalePanel = new java.awt.Panel();
        xScaleLabel = new java.awt.Label();
        xScaleTextField = new java.awt.TextField();
        yScaleLabel = new java.awt.Label();
        yScaleTextField = new java.awt.TextField();
        zScaleLabel = new java.awt.Label();
        zScaleTextField = new java.awt.TextField();
        buttonPanel = new java.awt.Panel();
        cancelButton = new java.awt.Button();
        continueButton = new java.awt.Button();
        label = new java.awt.Label();

        setLayout(new java.awt.GridBagLayout());

        scalePanel.setLayout(new java.awt.GridBagLayout());

        xScaleLabel.setText("X-scale:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        scalePanel.add(xScaleLabel, gridBagConstraints);

        xScaleTextField.setText("1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        scalePanel.add(xScaleTextField, gridBagConstraints);

        yScaleLabel.setText("Y-scale:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        scalePanel.add(yScaleLabel, gridBagConstraints);

        yScaleTextField.setText("1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        scalePanel.add(yScaleTextField, gridBagConstraints);

        zScaleLabel.setText("Z-scale:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        scalePanel.add(zScaleLabel, gridBagConstraints);

        zScaleTextField.setText("1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        scalePanel.add(zScaleTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(scalePanel, gridBagConstraints);

        cancelButton.setLabel("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        continueButton.setLabel("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(continueButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(buttonPanel, gridBagConstraints);

        label.setText("Please enter scale of image:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(label, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		calibration.pixelWidth = new Float(xScaleTextField.getText()).floatValue();
		calibration.pixelHeight = new Float(yScaleTextField.getText()).floatValue();
		calibration.pixelDepth = new Float(zScaleTextField.getText()).floatValue();
		frame.scaleOptionPanelCancelButtonPressed();
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
		calibration.pixelWidth = new Float(xScaleTextField.getText()).floatValue();
		calibration.pixelHeight = new Float(yScaleTextField.getText()).floatValue();
		calibration.pixelDepth = new Float(zScaleTextField.getText()).floatValue();
		frame.scaleOptionPanelContinueButtonPressed();
	}//GEN-LAST:event_continueButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel buttonPanel;
    private java.awt.Button cancelButton;
    private java.awt.Button continueButton;
    private java.awt.Label label;
    private java.awt.Panel scalePanel;
    private java.awt.Label xScaleLabel;
    private java.awt.TextField xScaleTextField;
    private java.awt.Label yScaleLabel;
    private java.awt.TextField yScaleTextField;
    private java.awt.Label zScaleLabel;
    private java.awt.TextField zScaleTextField;
    // End of variables declaration//GEN-END:variables
}
