
import java.util.logging.Level;

/*
 * SecondaryStackOptionDialog.java
 *
 * Created on November 13, 2008, 5:40 PM
 */
import java.util.logging.Logger;



/**
 *
 * @author  pawel
 */
public class SecondaryStackOptionDialog extends java.awt.Dialog {
    
    /** Creates new form SecondaryStackOptionDialog */
    public SecondaryStackOptionDialog(MainFrame f) {
        super(f, "Secondary stack option", false);
        frame  = f;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label1 = new java.awt.Label();
        continueButton = new java.awt.Button();
        cancelButon = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setText("Make secondary stack active and press Ok to measure intensity levels.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(label1, gridBagConstraints);

        continueButton.setLabel("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(continueButton, gridBagConstraints);

        cancelButon.setLabel("Cancel");
        cancelButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(cancelButon, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        try {
			frame.secondaryStackOptionPanelContinueButtonPressed();
                        setVisible(false);
                        dispose();
		} catch (Exception ex) {
			Logger.getLogger(SecondaryStackOptionPanel.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_continueButtonActionPerformed

    private void cancelButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButonActionPerformed
        frame.secondaryStackOptionPanelCancelButtonPressed();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButonActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run(MainFrame f) {
//                SecondaryStackOptionDialog dialog = new SecondaryStackOptionDialog(f, true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    private MainFrame frame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cancelButon;
    private java.awt.Button continueButton;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
    
}
