
import java.util.logging.Level;
import java.util.logging.Logger;

public class SecondaryStackOptionPanel extends java.awt.Panel {
	MainFrame frame;
	
	SecondaryStackOptionPanel(MainFrame frame) {
		initComponents();
		this.frame = frame;
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label = new java.awt.Label();
        buttonPanel = new java.awt.Panel();
        cancelButton = new java.awt.Button();
        continueButton = new java.awt.Button();

        setLayout(new java.awt.GridBagLayout());

        label.setText("Make secondary stack active and press Ok to measure intensity levels.");
        add(label, new java.awt.GridBagConstraints());

        cancelButton.setLabel("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        continueButton.setLabel("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(continueButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(buttonPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

	private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
		try {
			frame.secondaryStackOptionPanelContinueButtonPressed();//GEN-LAST:event_continueButtonActionPerformed
		} catch (Exception ex) {
			Logger.getLogger(SecondaryStackOptionPanel.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		frame.secondaryStackOptionPanelCancelButtonPressed();
	}//GEN-LAST:event_cancelButtonActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel buttonPanel;
    private java.awt.Button cancelButton;
    private java.awt.Button continueButton;
    private java.awt.Label label;
    // End of variables declaration//GEN-END:variables
	
}
