public class SecondaryStackOptionPanel extends java.awt.Panel {
	MainFrame frame;
	
	SecondaryStackOptionPanel(MainFrame frame) {
		initComponents();
		this.frame = frame;
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label = new java.awt.Label();
        okButton = new java.awt.Button();

        setLayout(new java.awt.GridBagLayout());

        label.setText("Make secondary stack active and press Ok to measure intensity levels.");
        add(label, new java.awt.GridBagConstraints());

        okButton.setLabel("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(okButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		frame.secondaryStackChooserButtonPressed();
	}//GEN-LAST:event_okButtonActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label;
    private java.awt.Button okButton;
    // End of variables declaration//GEN-END:variables
	
}
